--∆Æ∑ª¿Ëº«

create table dept_tcl
 as SELECT * FROM DEPT;
 
SELECT * FROM DEPT_TCL;
 
INSERT INTO DEPT_TCL VALUES(50,'DATABASE','SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO =40;
DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

ROLLBACK;
COMMIT;


--11-7
DELETE FROM DEPT_TCL WHERE DEPTNO = 50;

SELECT * FROM DEPT_TCL;
COMMIT;


--11-10
UPDATE DEPT_TCL SET LOC='SEOUL'
WHERE DEPTNO = 30;
COMMIT;




--ø¨Ω¿πÆ¡¶
CREATE TABLE DEPT_HW 
  AS SELECT * FROM DEPT;

--1
UPDATE DEPT_HW 
 SET DNAME = 'DATABASE',LOC='SEOUL'
WHERE DEPTNO = 30;
ROLLBACK;
SELECT * FROM DEPT_HW;
