--12장

--테이블생성 CREATE 
--12-1
CREATE TABLE EMP_DDL(
   EMPNO  NUMBER(4),
   ENAME VARCHAR2(10),
   JOB   VARCHAR2(9),
   MGR  NUMBER(4),
   HIREDATE  DATE,--날짜형식
   SAL  NUMBER(7,2),--숫자7자리 소수점2자리까지
   COMM NUMBER(7,2),
   DEPTNO  NUMBER(2)
 );
 
 DESC EMP_DDL; --테이블 구조확인
 DESC EMP;
 
 
 
 --12-2 테이블복사 단,제약조건은 복사 불가능(기본키,외래키,NOT NULL....등)
 CREATE TABLE DEPT_DDL
   AS SELECT * FROM DEPT;

SELECT * FROM DEPT_DDL;
DESC DEPT_DDL;
DESC DEPT;





--테이블 변경 ALTER

CREATE TABLE EMP_ALTER 
  AS SELECT * FROM EMP;

DESC EMP_ALTER;
SELECT * FROM EMP_ALTER;


--12-7 열추가 DDA
ALTER TABLE EMP_ALTER ADD HP VARCHAR2(20);


--12-8 열의 이름변경 RENAME
ALTER TABLE EMP_ALTER RENAME COLUMN HP TO TEL;


--12-9 열의 자료형변경 MODIFY
ALTER TABLE EMP_ALTER MODIFY EMPNO NUMBER(5);


--12-10 열을 삭제할때 DROP
ALTER TABLE EMP_ALTER DROP COLUMN TEL;



--테이블 이름변경 RENAME

--12-11 이름변경 RENAME
RENAME EMP_ALTER TO EMP_RENAEM;
RENAME EMP_RENAEM TO EMP_RENAME;
SELECT * FROM EMP_RENAME;



--테이블 데이터를 삭제 TRUNCATE
--TRUNCATE 와 DELETE 차이점 : TRUNCATE은 롤백불가,DELETL는 롤백가능
DELETE FROM EMP_RENAME;
ROLLBACK;

--12-14
TRUNCATE TABLE EMP_RENAME;



--테이블 삭제 DROP 정의어는 자동커밋 됨으로 삭제후 찾을수업음
--12-15 
DROP TABLE EMP_RENAME;



--연습문제

--1
CREATE TABLE EMP_HW(
  EMPNO NUMBER(4),
  ENAME VARCHAR2(10),
  JOB VARCHAR2(9),
  MGR NUMBER(4),
  HIREDATE DATE,
  SAL NUMBER(7,2),
  COMM NUMBER(7,2),
  DEPTNO NUMBER(2)
);

--2
ALTER TABLE EMP_HW ADD BIGO VARCHAR2(20);
SELECT * FROM EMP_HW;

--3
ALTER TABLE EMP_HW MODIFY BIGO VARCHAR2(30);
DESC EMP_HW;

--4
ALTER TABLE EMP_HW RENAME COLUMN BIGO TO REMARK;

--5
INSERT INTO EMP_HW( EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,REMARK)
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL 
  FROM EMP;
  
--6
DROP TABLE EMP_HW;

