--14장
--NOT UNLL
CREATE TABLE TABLE_NOTNULL(
    LOGIN_ID VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20)
    );
DESC table_notnull;

-- NULL값을 입력시 에러발생
INSERT INTO table_notnull VALUES('01','1234','010-1234-1234');
INSERT INTO table_notnull VALUES('02','5678',NULL);
SELECT * FROM table_notnull;

-- 제약조건 확인
-- 왼쪽 테이블을 클릭해서 확인가능


-- 제약조건의 이름을 직접 지정 (보통 이름은 테이블이름_열이름_제약조건)
CREATE TABLE NOTNULL2 (
    LOGIN_ID VARCHAR2(20) CONSTRAINT NN2_ID_NN NOT NULL,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT NN2_PW_NN NOT NULL,
    TEL VARCHAR2(20)
    );


-- 이미 생성된 테이블에 제약조건 추가  (14-7)
ALTER TABLE NOTNULL2
MODIFY(TEL NOT NULL);

DESC notnull2;


-- 제약조건 삭제
ALTER TABLE NOTNULL2 DROP CONSTRAINT NN2_ID_NN;
ALTER TABLE NOTNULL2 DROP CONSTRAINT NN2_PW_NN;

-- 테이블 정리
DROP TABLE table_notnull;




--중복되지 않는 값 UNIQUE
DROP TABLE 유니크;
CREATE TABLE 유니크(
  LOGIN_ID VARCHAR2(20) CONSTRAINT U_ID_UK UNIQUE,
  LOGIN_PWD VARCHAR2(20) NOT NULL,
  TEL VARCHAR2(20)
  );

--중복 안되는지 확인
INSERT INTO 유니크 VALUES('01','1234','010-1234-1234');
INSERT INTO 유니크 VALUES('01','5678','010-5678-5678');




--PK 기본키(UK + NN)
CREATE TABLE 기본키(
  LOGIN_ID VARCHAR2(20) CONSTRAINT P_ID_PK PRIMARY KEY,
  LOGIN_PWD VARCHAR2(20) NOT NULL,
  TEL VARCHAR2(20)
  );
CREATE TABLE 기본키2(
  LOGIN_ID VARCHAR2(20) ,
  LOGIN_PWD VARCHAR2(20) NOT NULL,
  TEL VARCHAR2(20),
  PRIMARY KEY(LOGIN_ID)
  );

DESC 기본키;
--에러나는 경우
INSERT INTO 기본키 VALUES('01','1234','010-1234-1234');
INSERT INTO 기본키 VALUES(NULL,'5678','010-5678-5678');
INSERT INTO 기본키 VALUES('01','5678','010-5678-5678');





--외래키
INSERT INTO EMP VALUES(9999,'홍길동','CLERK','7788','2017/04/30',1200,NULL,NULL);
INSERT INTO EMP VALUES(7777,'홍길동','CLERK','7788','2017/04/30',1200,NULL,10);
SELECT * FROM EMP;
ROLLBACK;

--외래키 테이블 만들기 1. 참조테이블 필요

DROP TABLE 참조;
DROP TABLE 외래키;

CREATE TABLE 참조(
  DEPTNO NUMBER(2) PRIMARY KEY,
  DNAME VARCHAR2(14),
  LOC VARCHAR2(20)
  );

--외래키 설정시 : 기본키와 같은 타입이여야함,REFERENCES 참조할테이블명(컬럼명)
--옵션
--ON DELETE CASCADE : 참조테이블의 데이터삭제시 참조하고있는 테이블에서 관련 행도 같이삭제,
--ON DELETE SET NULL : 참조테이블의 데이터를 삭제시 참조하고있는 테이블에서 관련행에 NULL값 입력
CREATE TABLE 외래키(
 EMPNO NUMBER(4) PRIMARY KEY,
 ENAME VARCHAR2(20),
 JOB VARCHAR2(20),
 SAL NUMBER(7,2),
 DEPTNO NUMBER(2) CONSTRAINT DEPTNO_FK REFERENCES 참조(DEPTNO) ON DELETE SET NULL
 );


--참조테이블 데이터 삽입 
INSERT INTO 참조 VALUES(10,'개발부','서울');
INSERT INTO 참조 VALUES(20,'마케팅부','부산');
INSERT INTO 참조 VALUES(30,'영업부','대전');
SELECT * FROM 참조;

--외래키 테이블 데이터 삽입
INSERT INTO 외래키 VALUES(1234,'홍길동','매니저',3000,10);
INSERT INTO 외래키 VALUES(1235,'강감찬','매니저',5000,20);
INSERT INTO 외래키 VALUES(1236,'이순신','매니저',7000,30);
INSERT INTO 외래키 VALUES(1237,'아무개','사장',10000,NULL);
SELECT * FROM 외래키;
--에러나는 경우
INSERT INTO 외래키 VALUES(1238,'홍길동','매니저',3000,40);
DELETE FROM 참조 WHERE DEPTNO = 10;





--CHECK 제약조건
--LENGTH 길이를 뜻함
CREATE TABLE 체크(
  LOGIN_ID VARCHAR2(20) PRIMARY KEY,
  LOGIN_PWD VARCHAR2(20) CHECK (LENGTH(LOGIN_PWD)>3),
  SAL NUMBER(4) CHECK (SAL>1000)
  );

--데이트입력
INSERT INTO 체크 VALUES('01','1234',2000);

--오류나는 경우 -체크 제약조건이 맞지 않을때
INSERT INTO 체크 VALUES('01','123',2000);
INSERT INTO 체크 VALUES('02','12345',1000);




--DEFAULT값(기본값) 설정(NULL값대신)
--값을 안적으면 DEFAULT값이 입력됨
CREATE TABLE 디폴트(
  LOGIN_ID VARCHAR2(20) PRIMARY KEY,
  LOGIN_PWD VARCHAR2(20) CHECK (LENGTH(LOGIN_PWD)>3),
  SAL NUMBER(4) DEFAULT 2000 CHECK (SAL>1000) 
  );
  
--데이터 입력
INSERT INTO 디폴트(LOGIN_ID,LOGIN_PWD) VALUES('02','1234');
SELECT * FROM 디폴트;




--연습문제

--1
CREATE TABLE DEPT_CONST (
 DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK  PRIMARY KEY,
 DNAME VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
 LOC VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
 );
 
--2
CREATE TABLE EMP_CONST(
 EMPNO NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
 ENAME VARCHAR(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
 JOB VARCHAR(9),
 TEL VARCHAR(20)CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
 HIREDATE DATE,
 SAL NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK CHECK (SAL>1000 AND SAL<9999),
 COMM NUMBER(7,2),
 DEPTNO NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST(DEPTNO)
 );
