--9-1
SELECT SAL FROM EMP WHERE ENAME= 'JONES';
--9-2
SELECT * FROM EMP WHERE SAL>2975;
--9-3 존스보다 급여를 많이받는사람출력
SELECT * FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME= 'JONES');

--9-4
SELECT * FROM EMP WHERE HIREDATE <(SELECT HIREDATE FROM EMP WHERE ENAME = 'SCOTT');
--9-5서브쿼리안에 함수사용
SELECT E.EMPNO,E.ENAME,E.JOB,E.SAL,D.DEPTNO,D.DNAME,D.LOC 
FROM EMP E JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO 
WHERE E.DEPTNO =20 
AND E.SAL > (SELECT AVG(SAL) FROM EMP);--AVG평균

--9-6부서번호가20 이거나 30인사원의 정보만 출력
SELECT * FROM EMP WHERE DEPTNO IN (20,30);
--9-7부서별 최고 급여와 동일한 급여를 받는 사원 출력
SELECT * FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
--9-9 ANY 연산자는 앞에 비교연산자(=,>=,<=등)사용해야함, 하나라도 참이면 모두참
SELECT * FROM EMP WHERE SAL < ANY (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

--9-14 ALL 연산자 : 모든결과값이 참이여야 출력
SELECT * FROM EMP WHERE SAL < ALL (SELECT SAL FROM EMP WHERE DEPTNO =30);

--9-18 다중행서브쿼리: 열이2개이상 연산자는IN
SELECT * FROM EMP WHERE (DEPTNO,SAL) IN (SELECT DEPTNO,MAX(SAL) FROM EMP GROUP BY DEPTNO);
--9-21 SELECT 절에사용하는 서브쿼리 
SELECT EMPNO,ENAME,JOB,SAL,(SELECT GRADE FROM SALGRADE WHERE E.SAL BETWEEN LOSAL AND HISAL) AS 급여등급,
      DEPTNO,(SELECT DNAME FROM DEPT WHERE E.DEPTNO = DEPT.DEPTNO) AS 부서명
FROM EMP E;



--예제문
SELECT JOB,EMPNO,ENAME,SAL,DEPTNO,(SELECT DNAME FROM DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO)AS DNAME
FROM EMP 
WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME ='ALLEN');


--2
SELECT EMPNO,ENAME,(SELECT DNAME FROM DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO)AS DNAME,HIREDATE,
(SELECT LOC FROM DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO)AS LOC,SAL,(SELECT GRADE FROM SALGRADE WHERE EMP.SAL BETWEEN LOSAL AND HISAL) AS GRADE  
FROM EMP 
WHERE SAL >(SELECT AVG(SAL) FROM EMP) ORDER BY SAL DESC;


--3  DISTINCT중복제거
SELECT E.EMPNO,E.ENAME,E.JOB,E.DEPTNO,D.DNAME,D.LOC
FROM EMP E ,DEPT D 
WHERE E.DEPTNO = D.DEPTNO AND E.DEPTNO=10 AND JOB <> ALL(SELECT DISTINCT JOB FROM EMP WHERE DEPTNO = 30);

--4
SELECT E.EMPNO,E.ENAME,E.SAL,S.GRADE FROM EMP E ,SALGRADE S
WHERE E.SAL BETWEEN LOSAL AND HISAL AND
SAL>(SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN')ORDER BY E.EMPNO ASC ;

