--연습문제
--1
SELECT EMPNO,ENAME,SAL FROM EMP WHERE DEPTNO = 10;
--2
SELECT ENAME,HIREDATE,DEPTNO FROM EMP WHERE EMPNO=7369;
--3
Select * From Emp Where Ename= 'ALLEN';
--4
SELECT ENAME,DEPTNO,SAL FROM EMP WHERE HIREDATE='81/02/20';

--5
SELECT * FROM EMP WHERE NOT JOB='MANAGER';
SELECT * FROM EMP WHERE JOB <>'MANAGER';--<>,!=
--6
SELECT * FROM EMP WHERE HIREDATE>'81/04/02';
--7
SELECT ENAME,SAL,DEPTNO FROM EMP WHERE SAL>=800;
--8
SELECT * FROM EMP WHERE DEPTNO>=20;
--9
SELECT * FROM EMP WHERE ENAME >='L';
--10
SELECT * FROM EMP WHERE HIREDATE<'81/12/09';
--11
SELECT EMPNO, ENAME FROM EMP WHERE EMPNO<=7698;
--12
SELECT ENAME, SAL, DEPTNO FROM EMP WHERE HIREDATE>='81/04/02' AND HIREDATE<='82/12/09'; 
--13
SELECT ENAME,JOB,SAL FROM EMP WHERE SAL >1600 AND SAL<3000;
--14
SELECT * FROM EMP WHERE NOT EMPNO BETWEEN 7654 AND 7782;
SELECT * FROM EMP WHERE NOT EMPNO < 7654 AND EMPNO > 7782;
--15
SELECT * FROM EMP WHERE ENAME BETWEEN 'B' AND 'J';
SELECT * FROM EMP WHERE ENAME >= 'B' AND ENAME < 'J';
--16
SELECT * FROM EMP WHERE NOT(HIREDATE>='81/01/01' AND HIREDATE<='81/12/31');
SELECT * FROM EMP WHERE NOT HIREDATE BETWEEN '81/01/01' AND '81/12/31';

--17
SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB= 'SALESMAN';
--18
SELECT ENAME,EMPNO,DEPTNO FROM EMP WHERE DEPTNO<>20 AND DEPTNO<>30;
--19
SELECT EMPNO,ENAME,HIREDATE,DEPTNO FROM EMP WHERE ENAME LIKE 'S%';
--20
SELECT * FROM EMP WHERE HIREDATE BETWEEN'1981/01/01' AND '1981/12/31' ;
--21
SELECT * FROM EMP WHERE ENAME LIKE '%S%';
--22
SELECT * FROM EMP WHERE ENAME LIKE 'M____N';
--23
SELECT * FROM EMP WHERE ENAME LIKE '_A%';
--24
SELECT * FROM EMP WHERE COMM IS NULL;
--25
SELECT * FROM EMP WHERE COMM IS NOT NULL;
--26
SELECT ENAME, DEPTNO,SAL FROM EMP WHERE DEPTNO = 30 AND SAL>=1500;
--27
SELECT EMPNO,ENAME,DEPTNO FROM EMP WHERE ENAME LIKE 'K%' OR DEPTNO = 30;
--28
SELECT * FROM EMP WHERE SAL>=1500 AND DEPTNO =30 AND JOB='MANAGER';
--29
SELECT * FROM EMP WHERE DEPTNO = 30 ORDER BY EMPNO ASC;--오름차순(ASC)일땐 안적어도 됨
--30
SELECT * FROM EMP ORDER BY SAL DESC;
--31
SELECT * FROM EMP ORDER BY DEPTNO ASC,SAL DESC; --여러개 정렬시 , 사용
--32
SELECT DEPTNO,ENAME,SAL FROM EMP ORDER BY DEPTNO DESC,ENAME ASC,SAL DESC;
--33
SELECT ENAME,SAL,ROUND(SAL*0.13,0) AS BONUS,DEPTNO FROM EMP WHERE DEPTNO = 10; --AS생략가능
--34
SELECT ENAME,SAL,NVL(COMM,0),SAL+NVL(COMM,0) AS TOTAL FROM EMP ORDER BY TOTAL DESC;
--35
SELECT ENAME,SAL,CONCAT('$',ROUND(SAL*0.15,1))AS 회비 FROM EMP WHERE SAL BETWEEN 1500 AND 3000;
--회비는 달러표시$로 시작하고 소수점1자리까지 출려
SELECT ENAME,SAL,TO_CHAR(ROUND(SAL*0.15,1),'$999.9')AS 회비 FROM EMP WHERE SAL BETWEEN 1500 AND 3000;
--36. 사원수가 5명이 넘는 부서의 부서명과 사원수 조회
SELECT DEPT.DNAME , COUNT(*) FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO GROUP BY DEPT.DNAME HAVING COUNT(*)>5;
--37
SELECT JOB ,SUM(SAL) FROM EMP WHERE JOB<>'SALESMAN'GROUP BY JOB HAVING SUM(SAL)>5000 ORDER BY SUM(SAL) DESC;
--38
SELECT E.EMPNO,E.ENAME,E.SAL,S.GRADE FROM EMP E JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;
--39 COUNT(*)일때 널값이 있어도 계산가능
SELECT DEPTNO, COUNT(*) AS "사원수" ,COUNT(COMM) AS "커미션 받은 사원수" FROM EMP GROUP BY DEPTNO;
--40 부서번호가 10은'총무부' 20은'개발부' 30은'영업부'
SELECT ENAME,DEPTNO,DECODE(DEPTNO,10,'총무부',
                                  20,'개발부',
                                  30,'영업부') 부서명 FROM EMP;
SELECT ENAME,DEPTNO, CASE WHEN DEPTNO=10 THEN '총무부' WHEN DEPTNO =20 THEN '개발부' ELSE '영업부' END AS 부서명 FROM EMP;
